version: "3"
services:
  database:
    image: postgres:14-alpine
    restart: always
    volumes:
      - ./pg:/var/lib/postgresql/data
    environment:
      POSTGRES_DATABASE_LOCAL: writeme
      POSTGRES_DB: writeme
      POSTGRES_HOST_LOCAL: localhost
      POSTGRES_PASSWORD_LOCAL: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT_LOCAL: 5432
      POSTGRES_USER_LOCAL: postgres
    ports:
      - "5432:5432"
    networks:
      - network
  dev:
    image: node:16.13.0-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: /bin/sh -c "yarn ; yarn start:dev"
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - network
  test:
    image: node:16.13.0-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: /bin/sh -c "yarn test"
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - network
  build:
    image: node:16.13.0-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: /bin/sh -c "yarn build"
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - network
  start:
    image: node:16.13.0-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: /bin/sh -c "yarn start"
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - network
  tests:
    image: node
    working_dir: /app
    volumes:
      - ./app
    command: yarn jest
    environment:
      POSTGRES_HOST_LOCAL: "database"
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - network

networks:
  network:
    driver: bridge
