version: "3"
services:
  mysql:
    image: mysql:5.6
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: writeme
    ports:
      - "3306:3306"
    networks:
      - network
  postgres:
    image: postgres:14-alpine
    restart: always
    volumes:
      - ./pg:/var/lib/postgresql/data
    environment:
      POSTGRES_DATABASE_LOCAL: writeme
      POSTGRES_DB: writeme
      POSTGRES_HOST_LOCAL: localhost
      POSTGRES_PASSWORD_LOCAL: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT_LOCAL: 5432
      POSTGRES_USER_LOCAL: postgres
    ports:
      - "5432:5432"
    networks:
      - network

networks:
  network:
    driver: bridge
